"""add created_at to users

Revision ID: 3876cd3c3a52
Revises: add_memories_table
Create Date: 2025-07-01 08:36:31.066269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3876cd3c3a52'
down_revision: Union[str, Sequence[str], None] = 'add_memories_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('remind_at', sa.String(), nullable=False),
    sa.Column('shared_with_partner', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('quiz_questions', 'media_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.add_column('users', sa.Column('created_at', sa.String(length=32), nullable=True))
    op.execute("UPDATE users SET created_at = '1970-01-01'")
    op.alter_column('users', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.alter_column('quiz_questions', 'media_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.drop_table('reminders')
    # ### end Alembic commands ###
